### PR TITLE
Restrict bump's semver tracker to v1.x 

### PR DESCRIPTION
**Pull request by v1gnesh**

### CODE REVIEW

**Comment by IgorTodorovskiIBM** [comment]
Cool, so that will prevent picking up the bogus 6.6.6 version?

**Review by IgorTodorovskiIBM — APPROVED** [review]
LGTM

**Comment by v1gnesh** [comment]
> Cool, so that will prevent picking up the bogus 6.6.6 version?

@IgorTodorovskiIBM Yup. They've deleted the stray tag, but bump still picks up `2` from somewhere.
So restricting to `^1` will work for a while..

**Review by MikeFultonDev — APPROVED** [review]
LGTM

**Pull request merged**
